name: minion_practice
channels:
  - defaults
  - bioconda
dependencies:
  - porechop =0.2.4
  - nanofilt =2.8.0
  - python =3.10.12
  - blast >=2.14.0
  - minimap2 =2.26
  - samtools =1.17
  - diamond >=2.1.8
  - flye >=2.9.2
  - interproscan =5.59_91.0
